### zalogowany uzytkownik chce swoje dane
GET http://localhost:3500/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJ0ZXN0emFibG9rb3dhbnkiLCJpYXQiOjE2MDQ2MTI4NTF9.8J_t9tyW8LW3if3fpY6VmaM2TI75j4ROdD5DDpkie9M

### logowanie ok

POST http://localhost:3500/login
Content-Type: application/json

{
    "username": "wkuchta",
    "password": "wkuchta"
}

### logowanie ok

POST http://localhost:3500/login
Content-Type: application/json

{
    "username": "testzablokowany",
    "password": "testzablokowany"
}

### logowanie nie ok

POST http://localhost:3500/login
Content-Type: application/json

{
    "username": "cgrabowski",
    "password": "cgrabowski"
}


### odswiezanie tokena

POST http://localhost:3500/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibG9naW4iOiJ3a3VjaHRhIiwicGFzc3dvcmQiOiJ3a3VjaHRhIiwiaWF0IjoxNjA0NjA2MjI3fQ.2Md8hrareKjuAoIPLEpg5_qMlGrxfbSRmgS-bNMuvsM"
}